# Generated by Django 3.2 on 2024-01-11 18:21

from django.db import migrations, models
import django.db.models.deletion
import myapp.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, validators=[myapp.validators.validate_letters, myapp.validators.validate_first_letter], verbose_name='First Name')),
                ('last_name', models.CharField(max_length=255, validators=[myapp.validators.validate_letters, myapp.validators.validate_first_letter], verbose_name='Last Name')),
                ('document', models.CharField(max_length=14, unique=True, validators=[myapp.validators.validate_value], verbose_name='Document')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Balance')),
                ('user_type', models.CharField(choices=[['M', 'Merchant'], ['C', 'Common']], default='C', max_length=1, validators=[myapp.validators.validate_first_letter], verbose_name='User Type')),
            ],
            options={
                'verbose_name': 'CustomUser',
                'verbose_name_plural': 'CustomUsers',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[myapp.validators.validate_value], verbose_name='Transaction Amount')),
                ('transaction_date', models.DateTimeField(auto_now_add=True, validators=[myapp.validators.validate_date, myapp.validators.validate_time], verbose_name='Date and Time')),
                ('payee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='payee_transactions', to='myapp.customuser', verbose_name='Transaction Payee')),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='payer_transactions', to='myapp.customuser', verbose_name='Transaction Payer')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['id'],
            },
        ),
    ]
