# Generated by Django 3.2 on 2024-01-12 18:04

from django.db import migrations, models
import myapp.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, validators=[myapp.validators.validate_first_letter], verbose_name='Tool Title')),
                ('link', models.URLField(blank=True, validators=[myapp.validators.validate_first_letter])),
                ('description', models.TextField(max_length=200, validators=[myapp.validators.validate_first_letter])),
                ('tags', models.JSONField(blank=True, default=list, validators=[myapp.validators.validate_tag])),
            ],
            options={
                'verbose_name': 'Tool',
                'verbose_name_plural': 'Tools',
                'ordering': ['id'],
            },
        ),
    ]
