# Generated by Django 3.2 on 2024-01-12 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
