# Generated by Django 3.2 on 2024-01-11 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='document',
            field=models.CharField(max_length=14, unique=True, verbose_name='Document'),
        ),
    ]
